package com.example.tema3.constants;

public class Constants {
    public final static String EMAIL_ERROR_MESSAGE = "Enter your email";
    public final static String PASSWORD_ERROR_MESSAGE = "Enter your password";
    public final static String CONFIRM_PASSWORD_ERROR_MESSAGE = "Confirm your password";
    public final static String PASSWORDS_NOT_MATCHING_ERROR_MESSAGE = "Passwords do not match";
    public final static String INVALID_EMAIL_ERROR_MESSAGE = "Email is invalid !";
    public final static String PROGRESS_DIALOG_MESSAGE = "Please wait...";
    public final static String SUCCESSFUL_REGISTER_MESSAGE = "Successfully registered";
    public final static String FAILED_REGISTER_ERROR_MESSAGE = "Sign up failed";
    public final static String FAILED_LOGIN_ERROR_MESSAGE = "Login failed";
    public final static String SUCCESSFUL_LOGIN_MESSAGE = "Login successful";
    public final static String PASSWORD_LENGTH_ERROR_MESSAGE = "Password's length should be higher than or equal to 6";
    public final static String SUCCESSFUL_CHANGE_PASSWORD_MESSAGE = "E-mail for resetting password has been successfully sent !";
    public final static String FAILED_CHANGE_PASSWORD_ERROR_MESSAGE = "E-mail for resetting password couldn't be sent !";
    public final static String DEFAULT_COMMENTS_URL = "https://mocki.io/v1/c3fd5bf7-6725-4ec7-a156-e34b00f433a6";
    public final static String DEFAULT_COMMENTS_LOADING_ERROR = "Default comments (via JSON request) were not loaded";
    public final static String DEFAULT_COMMENTS_LOG_ERROR = "Comments loading error";
    public final static String SHARED_PREFERENCES_USER_EMAIL = "UserEmail";
    public final static String SUCCESSFUL_DELETION_MESSAGE = "Successful deletion!";
    public final static String FAILED_DELETION_MESSAGE = "Failed deletion !";
    public final static String CANCELLED_DELETION_MESSAGE = "Deletion has been cancelled!";
    public final static String CANCELLED_ADD_UPDATE_MESSAGE = "Addition/update has been cancelled!";
    public final static String NO_TOPICS_SELECTED_MESSAGE = "Select a topic first!";
    public final static String TOO_MANY_TOPICS_SELECTED_MESSAGE = "Only one topic can be edited at a time!";
    public final static String SUCCESSFUL_ADDITION_MESSAGE = "The topic has been successfully added !";
    public final static String INVALID_INPUT_MESSAGE = "Your input is not valid (empty strings are not allowed) !";
    public final static String TOPIC_ALREADY_EXISTS_MESSAGE = "A topic with the provided title already exists!";
    public final static String EMPTY_COMMENT_MESSAGE = "You cannot leave an empty comment!";
    public final static String EMPTY_TITLE_MESSAGE = "The title cannot be empty!";
    public final static String EMPTY_DESCRIPTION_MESSAGE = "The description cannot be empty!";
    public final static String SUCCESSFUL_COMMENT_ADDITION_MESSAGE = "The comment has been successfully added!";
    public final static String CANCELLED_TOPIC_UPDATE_MESSAGE = "The topic's update has been cancelled!";
    public final static String CANCELLED_COMMENT_SOLUTION_MARKING_MESSAGE = "The comment's solution marking has been cancelled!";
    public final static String CANCELLED_SPECIFIC_COMMENTS_ADDITION_MESSAGE = "The specific comments addition has been cancelled!";
    public final static String CANCELLED_COMMENT_ADDITION_MESSAGE = "Comment addition has been cancelled!";
    public final static String CANCELLED_TOPICS_REALTIME_CONNECTION_MESSAGE = "The connection of the topics fragment with the realtime database has been cancelled!";
    public final static String CANCELLED_MANAGEMENT_REALTIME_CONNECTION_MESSAGE = "The connection of the management fragment with the realtime database has been cancelled!";
    public final static String SUCCESSFUL_DEFAULT_COMMENT_DELETION_MESSAGE = "The default comment has been successfully deleted!";
    public final static String SUCCESSFUL_DATABASE_COMMENT_DELETION_MESSAGE = "The comment has been successfully deleted from the DB!";
    public final static String SUCCESSFUL_TOPIC_UPDATE_MESSAGE = "The topic details have been successfully updated!";
    public final static String STRING_EMPTY = "";
    public final static int THREAD_SLEEP_VALUE = 1500;
}
